FROM mambaorg/micromamba:latest@sha256:128f5db84d6d1ba346885552bd7006f7067387bee85ba9b616d2b8e01026e6a1 as base

LABEL org.opencontainers.image.authors="Shiv Upadhyay <shivnupadhyay@gmail.com>, Eric Berquist <eric.berquist@gmail.com>"

ENV HOME /home/micromamba

COPY condarc "$HOME"/.mambarc
COPY environment.yml "$HOME"/environment.yml

RUN micromamba info && \
    micromamba install -n base -f "$HOME"/environment.yml

RUN gosu apt-get update && \
    gosu apt-get install -y -qq --no-install-recommends \
      build-essential \
      curl \
      gcc \
      git \
      swig \
    && rm -rf /var/lib/apt/lists/*
WORKDIR "$HOME"
RUN curl -o requirements.txt \
    https://raw.githubusercontent.com/berquist/cclib/pyquante2/requirements.txt \
    && cat requirements.txt
# RUN which python && \
#     python -m pip install --no-cache-dir -r requirements.txt

# Local Variables:
# mode: dockerfile
# End:
