FROM condaforge/miniforge3:latest@sha256:66776623eac99e25a397e358392663833a0d8c5beb2ed363cbf4ab19e169f728 as base

LABEL org.opencontainers.image.authors="Shiv Upadhyay <shivnupadhyay@gmail.com>, Eric Berquist <eric.berquist@gmail.com>"

ENV HOME /root

COPY condarc "$HOME"/.condarc
COPY environment.yml "$HOME"/environment.yml

RUN conda info -a && \
    conda env create -n cclib -f "$HOME"/environment.yml

RUN apt-get update && \
    apt-get install -y -qq --no-install-recommends \
      build-essential \
      curl \
      gcc \
      git \
      swig \
    && rm -rf /var/lib/apt/lists/*
RUN curl -o requirements \
    https://raw.githubusercontent.com/berquist/cclib/pyquante2/requirements.txt \
    && cat requirements.txt
RUN echo ". /opt/conda/etc/profile.d/conda.sh && conda activate cclib" > "$HOME"/.bashrc
SHELL ["/bin/bash", "-l", "-c"]
RUN which python && \
    python -m pip install --no-cache-dir -r requirements.txt

# Local Variables:
# mode: dockerfile
# End:
