FROM condaforge/mambaforge:latest@sha256:050753d138b6708128c9bb45055a9d943f06363f32f63a96f7dd5f304ada52a6 as conda

LABEL authors="Shiv Upadhyay <shivnupadhyay@gmail.com>, Eric Berquist <eric.berquist@gmail.com>"

COPY ./condarc /root/.condarc
COPY ./environment.yml /tmp/

RUN mamba info -a
RUN --mount=type=cache,target=/opt/conda/pkgs mamba env create -f /tmp/environment.yml -p /env

RUN apt-get update && \
    apt-get install -y -qq  --no-install-recommends \
      curl \
      gcc \
      swig
RUN curl -o requirements.txt \
    https://raw.githubusercontent.com/cclib/cclib/master/requirements.txt \
    && cat requirements.txt
RUN conda run -p /env python -m pip install -r requirements.txt

FROM gcr.io/distroless/base-debian10:debug@sha256:0828a5cfb40820d9110d4fb379edfca129ff5ec01d32d4f8acfd60173e2c49f3

COPY --from=conda /env /env

# Local Variables:
# mode: dockerfile
# End:
